# coding: utf-8

"""
    Deep Cloud API

    Deep Cloud description.

    OpenAPI spec version: 1.0.0
    Contact: sjs7007@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class MNISTApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def get_aqi(self, width, height, n_class, alpha, upload, **kwargs):
        """
        
        Allows user to upload the [MNIST dataset](https://drive.google.com/open?id=0B-HwpreJA3WzbnZodkJZVWNfUTg) and get a trained model based on the parameters specified. Description about the dataset can be found [here](http://yann.lecun.com/exdb/mnist/). 

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_aqi(width, height, n_class, alpha, upload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int width: width of image (required)
        :param int height: height of image (required)
        :param int n_class: number of classes (required)
        :param float alpha: learning rate (required)
        :param file upload: [MNIST dataset](https://drive.google.com/open?id=0B-HwpreJA3WzbnZodkJZVWNfUTg) (required)
        :return: InlineResponse2001
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_aqi_with_http_info(width, height, n_class, alpha, upload, **kwargs)
        else:
            (data) = self.get_aqi_with_http_info(width, height, n_class, alpha, upload, **kwargs)
            return data

    def get_aqi_with_http_info(self, width, height, n_class, alpha, upload, **kwargs):
        """
        
        Allows user to upload the [MNIST dataset](https://drive.google.com/open?id=0B-HwpreJA3WzbnZodkJZVWNfUTg) and get a trained model based on the parameters specified. Description about the dataset can be found [here](http://yann.lecun.com/exdb/mnist/). 

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_aqi_with_http_info(width, height, n_class, alpha, upload, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int width: width of image (required)
        :param int height: height of image (required)
        :param int n_class: number of classes (required)
        :param float alpha: learning rate (required)
        :param file upload: [MNIST dataset](https://drive.google.com/open?id=0B-HwpreJA3WzbnZodkJZVWNfUTg) (required)
        :return: InlineResponse2001
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['width', 'height', 'n_class', 'alpha', 'upload']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_aqi" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'width' is set
        if ('width' not in params) or (params['width'] is None):
            raise ValueError("Missing the required parameter `width` when calling `get_aqi`")
        # verify the required parameter 'height' is set
        if ('height' not in params) or (params['height'] is None):
            raise ValueError("Missing the required parameter `height` when calling `get_aqi`")
        # verify the required parameter 'n_class' is set
        if ('n_class' not in params) or (params['n_class'] is None):
            raise ValueError("Missing the required parameter `n_class` when calling `get_aqi`")
        # verify the required parameter 'alpha' is set
        if ('alpha' not in params) or (params['alpha'] is None):
            raise ValueError("Missing the required parameter `alpha` when calling `get_aqi`")
        # verify the required parameter 'upload' is set
        if ('upload' not in params) or (params['upload'] is None):
            raise ValueError("Missing the required parameter `upload` when calling `get_aqi`")


        collection_formats = {}

        resource_path = '/uploadCompleteScript'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'width' in params:
            form_params.append(('width', params['width']))
        if 'height' in params:
            form_params.append(('height', params['height']))
        if 'n_class' in params:
            form_params.append(('nClass', params['n_class']))
        if 'alpha' in params:
            form_params.append(('alpha', params['alpha']))
        if 'upload' in params:
            local_var_files['upload'] = params['upload']

        body_params = None

        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['text'])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['multipart/form-data'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='InlineResponse2001',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'),
                                            _return_http_data_only=params.get('_return_http_data_only'),
                                            _preload_content=params.get('_preload_content', True),
                                            _request_timeout=params.get('_request_timeout'),
                                            collection_formats=collection_formats)
