# coding: utf-8

"""
    Deep Cloud API

    Deep Cloud description.

    OpenAPI spec version: 1.0.0
    Contact: sjs7007@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2001(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, accuracy=None, trained_model=None):
        """
        InlineResponse2001 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'accuracy': 'str',
            'trained_model': 'str'
        }

        self.attribute_map = {
            'accuracy': 'Accuracy',
            'trained_model': 'trainedModel'
        }

        self._accuracy = accuracy
        self._trained_model = trained_model


    @property
    def accuracy(self):
        """
        Gets the accuracy of this InlineResponse2001.


        :return: The accuracy of this InlineResponse2001.
        :rtype: str
        """
        return self._accuracy

    @accuracy.setter
    def accuracy(self, accuracy):
        """
        Sets the accuracy of this InlineResponse2001.


        :param accuracy: The accuracy of this InlineResponse2001.
        :type: str
        """

        self._accuracy = accuracy

    @property
    def trained_model(self):
        """
        Gets the trained_model of this InlineResponse2001.


        :return: The trained_model of this InlineResponse2001.
        :rtype: str
        """
        return self._trained_model

    @trained_model.setter
    def trained_model(self, trained_model):
        """
        Sets the trained_model of this InlineResponse2001.


        :param trained_model: The trained_model of this InlineResponse2001.
        :type: str
        """

        self._trained_model = trained_model

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
