# coding: utf-8

"""
    Deep Cloud API

    Deep Cloud description.

    OpenAPI spec version: 1.0.0
    Contact: sjs7007@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.inline_response_200 import InlineResponse200
from .models.inline_response_200_1 import InlineResponse2001

# import apis into sdk package
from .apis.mnist_api import MNISTApi
from .apis.mnist_predictor_api import MNISTPredictorApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
