---
swagger: "2.0"
info:
  description: "Deep Cloud description."
  version: "1.0.0"
  title: "Deep Cloud API"
  termsOfService: "http://helloreverb.com/terms/"
  contact:
    name: "Saravanan Setty"
    email: "sjs7007@gmail.com"
  license:
    name: "MIT"
    url: "http://opensource.org/licenses/MIT"
host: "localhost:8888"
schemes:
- "http"
consumes:
- "multipart/form-data"
produces:
- "application/text"
paths:
  /MNISTPredictor:
    post:
      tags:
      - "MNISTPredictor"
      description: "Allows user to upload MNIST images and get predictions on a pretrained\
        \ model."
      operationId: "getAQI2"
      consumes:
      - "multipart/form-data"
      produces:
      - "text"
      parameters:
      - name: "upload"
        in: "formData"
        description: "MNIST image"
        required: true
        type: "file"
      responses:
        200:
          description: "JSON with prediction"
          schema:
            $ref: "#/definitions/inline_response_200"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "MNISTPredictor"
  /uploadCompleteScript:
    post:
      tags:
      - "MNIST"
      description: "Allows user to upload the [MNIST dataset](https://drive.google.com/open?id=0B-HwpreJA3WzbnZodkJZVWNfUTg)\
        \ and get a trained model based on the parameters specified. Description about\
        \ the dataset can be found [here](http://yann.lecun.com/exdb/mnist/). "
      operationId: "getAqi"
      consumes:
      - "multipart/form-data"
      produces:
      - "text"
      parameters:
      - name: "width"
        in: "formData"
        description: "width of image"
        required: true
        type: "integer"
        default: 28
      - name: "height"
        in: "formData"
        description: "height of image"
        required: true
        type: "integer"
        default: 28
      - name: "nClass"
        in: "formData"
        description: "number of classes"
        required: true
        type: "integer"
        default: 10
      - name: "alpha"
        in: "formData"
        description: "learning rate"
        required: true
        type: "number"
        default: 0.01000000000000000020816681711721685132943093776702880859375
      - name: "upload"
        in: "formData"
        description: "[MNIST dataset](https://drive.google.com/open?id=0B-HwpreJA3WzbnZodkJZVWNfUTg)"
        required: true
        type: "file"
      responses:
        200:
          description: "JSON with accuracies at different epochs, model path"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        500:
          description: "process got killed / tensorflow crashed"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "MNIST"
definitions:
  inline_response_200_1:
    properties:
      Accuracy:
        type: "string"
      trainedModel:
        type: "string"
  inline_response_200:
    properties:
      Prediction:
        type: "string"
